


pub struct HTTPRequest{
	accept: str,
	accept_charset: str,
	accept_encoding: str,
	accept_language: str,
	accept_date_time: str, 
	access_ctrl_req_method: str,
	authorization: str,
	cache_ctrl: str,
	connection: str,
	cookie: str,
	content_length: str,
	content_md5: str,
	content_type: str, 
	date: str,
	expect: str,
	forwarded: str,
	from: str,
	host: str,
	if_match: str,
	if_mod_since: str,
	if_range: str,
	if_unmod_since: str,
	max_fwd: str,
	origin: str,
	pragma: str,
	proxy_auth: str,
	range: str, 
	referer: str,
	te: str,
	user_agent: str,
	upgrade: str,
	warning: str,
}